# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='email',
        ),
        migrations.AddField(
            model_name='observations',
            name='authors',
            field=models.ManyToManyField(to='todo.Author'),
        ),
    ]
